### ISSUE TITLE
getting started guide broken by added commit

### ISSUE THREAD

**Issue by rfulwell** [hashicorp/tfc-guide-example#114]
https://learn.hashicorp.com/tutorials/terraform/cloud-change?in=terraform/cloud-get-started

This demo PR no longer has changes between `add-username` and `master`:
https://github.com/hashicorp/tfc-guide-example/compare/master...add-username

This is because this change should not have been merged to master:
https://github.com/hashicorp/tfc-guide-example/pull/108/files

**Comment by im2nguyen** [comment]
Thanks for flagging this! The changes should now be reflected in `master`
