### ISSUE TITLE
Speculative Run Failed: Reference to undeclared input variable - tag_user_name

### ISSUE THREAD

**Issue by Axatchaudhary** [hashicorp/tfc-guide-example#130]
I am new to Terraform Cloud and I am following exact same steps [this](https://learn.hashicorp.com/tutorials/terraform/cloud-change) tutorial. Turns out the first problem I faced was that while trying to create a [PR](https://github.com/Axatchaudhary/tfc-guide-example/pull/1) `master <- add-user-name`. There was no diff showed. However after resolving that by making my own little changes to get this to work, I faced another problem. Now the Terraform Test is failing. See the screenshot:

<img width="1223" alt="Screen Shot 2020-09-19 at 6 07 01 PM" src="https://user-images.githubusercontent.com/7285865/93692056-ed3c0100-faa2-11ea-8118-510ead1e4a74.png">

**Comment by im2nguyen** [comment]
Hi @Axatchaudhary , thank you for attempting the Learn tutorial. I believe you're using an older version of the repo, the new repo should **not** have `tag_user_name` as a variable.

This is a sample [PR](https://github.com/hashicorp/tfc-guide-example/pull/132) that merges `add-username` to the `branch`. As you can see, it adds the `Username` attribute to the configuration without the `tag_user_name` variable.

Please let me know if that helps!
