### ISSUE TITLE
Update the workflow

### ISSUE THREAD

**Issue by andrekolodochka** [hashicorp/tfc-guide-example#281]
I've created a PR #280 . It was closed automatically and I don't have an option to reopen it.

**Comment by andrekolodochka** [comment]
Also, `if you intended to edit the example itself please feel free to re-open it` comment is not helpful as majority of users won't be able to reopen the PR.

**Comment by im2nguyen** [comment]
Closing since this was addressed with https://github.com/hashicorp/tfc-guide-example/pull/280
