### ISSUE TITLE
Make this a public template repo

### ISSUE THREAD

**Issue by douglasnaphas** [hashicorp/tfc-guide-example#472]
[Creating from a public template](https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-repository-from-a-template) is easier than copying and pasting into a new repo.

**Comment by judithpatudith** [comment]
thank you for the suggestion! We've updated this tutorial so please see the new repo for it at https://github.com/hashicorp/learn-terraform-cloud. We have the user clone it and work through the CLI workflow first, and then add the directory to version control for the VCS workflow.
